language: perl
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get update
  - sudo apt-get install libdbus-1-3 libsdl1.2-dev
  - sudo apt-get install freeglut3-dev libxmu-dev
install: cpanm -v --installdeps --notest .
perl:
  - "5.18"
  - "5.16"

branches:
  only:
    - /^build/
